name: CI

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'The branch that will be used in the build'
        required: true
        default: 'main'   
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Prepare arguments workflow_dispatch
        if: ${{ github.event_name == 'workflow_dispatch'}}
        run: |
         echo "rosbot_stm32_firmware_ref=${{ github.event.inputs.target_branch }}" >> $GITHUB_ENV
      
      - name: Prepare arguments not workflow_dispatch
        if: ${{ github.event_name != 'workflow_dispatch'}}
        run: |
         echo "rosbot_stm32_firmware_ref=${{ github.ref }}" >> $GITHUB_ENV

      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          ref: ${{ env.rosbot_stm32_firmware_ref }}
          submodules: recursive
      
      - name: Installing platformio
        run: pip3 install -U platformio==6.1.6

      - name: Build current project using platformio 6.1.6 
        run: |
          pio lib install
          pio run
      
      - name: Prepare firmware files
        id: prepare
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          mkdir out
          cp ${{ github.workspace }}/.pio/build/core2_diff/firmware.bin out/firmware_diff.bin
          cp ${{ github.workspace }}/.pio/build/core2_mec/firmware.bin out/firmware_mec.bin

      - name: Upload firmware files
        uses: actions/upload-artifact@v2
        with:
          name: firmware_${{ steps.prepare.outputs.sha_short }}
          path: out/*